name: Deploy FastAPI to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install uvicorn

      - name: Create API Documentation
        run: |
          mkdir -p public
          cp app/index.html public/ || true
          echo "{
            \"status\": \"online\",
            \"timestamp\": \"2025-06-09 13:52:57\",
            \"user\": \"Dahbiadam\"
          }" > public/status.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
